language: node_js
node_js:
- 14
cache:
  bundler: true
  directories:
  - node_modules
script:
- npm test
after_deploy:
- bash .travis.push.sh
deploy:
  provider: npm
  email: mat@mlefree.com
  api_key: $NPM_TOKEN
  on:
    branch: master
