language: node_js
node_js:
- v8
install:
- npm install -g gulp
- npm install -g codecov
- npm install
- npm run install:after
script:
- npm test
- codecov
after_success:
- bash <(curl -s https://codecov.io/bash)
- npm install gulp
deploy:
  provider: npm
  email: mat@mlefree.com
  api_key:
    secure: F4wUxT5Ke7ebfRGt6NfHZCON06ibx/AqWYp5hNHbLMG7Amu5h24UfKhO6tw1DCR5IglqV5+0KkPvFSir6JTK1YJS1t0os9BiMdXoT8lNammQSQT8W+SCXHDqfPyUM5uO4d2v9CwXZXGQGyJ+qfyMidLfqY5w6eO9Ssob9xrv15vuv4B9Xd8VZIflKAYbXaoFryZa9yP3k/jNSbooA3KL3HP94sRGI6GmxOFeSMDipUuKkFjbVHB5Nws6iqTm6u3oLJaPzYA8hFUSv9WFofbuxjeJC7uk1nAlgymmnGMdojjcGmqDBujr4fLGSp5ckZ6yXqoHrd0ZTiueCr+sjJPkm2L8dqf59WGjZg/Jx1h/661AD3HyjS75LM+MHi+7fshkw8AzDeey+TX2/WGeUW6m4vZ6plTlPA+TCPOUuwj6/hZctNZ09mDU8unGyssI3UuR2lIhVb8L0t8PMDktbFAlIeVgUipn3wG8t5Y82HQQHW7oHE8iFpu+tKDqKx8woYiZbMA5CMnDf/qzb3RF2EhsRPPISkwBsui75ggWev07yxXwZZpaXqSoWncNhEap6qyp4tiDNEOI2BUkDPdKQoGDilipQdoeQLAwglj35cQ4O/rJOMQP7jLae4c+iXtYTTwHfvXvOwpiw46qPSQEt35S9lswmCxRRWWiAMMxiiq2mBI=
  on:
    branch: master
