language:
  - node_js
node_js:
   - 14
branches:
  only:
    - master
install:
 #- git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
 #- git fetch --tags --depth=10000
 - npm install
 #- npm version patch -m "[ci skip] version bumped %s"
script:
 - npm test
 - npm run build-prod
 - echo "myapp.com" > www/CNAME
after_success:
 #- git remote add upstream "https://${GH_TOKEN}@github.com/${GH_REPO}.git"
 #- git add .
 #- git commit -m "[ci skip] version ok"
 #- git push upstream HEAD:master
deploy:
  provider: pages
  local_dir: www
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  on:
    branch: master
env:
  global:
    - GH_REPO: "<%= appUserName %>/<%= appName %>"
